// AUTO-GENERATED — NE PAS MODIFIER MANUELLEMENT
// Genere par scripts/sync-client.ts depuis CLIENT.md
// Pour modifier: editer CLIENT.md puis lancer npm run sync-client

export const clientConfig = {
  NOM_ENTREPRISE: "K.B. COUVERTURE",
  NOM_LEGAL: "K.B. COUVERTURE EIRL",
  SIRET: "994 074 631 00000",
  METIER: "couvreur",
  METIER_LABEL: "Couvreur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Kévin",
  NOM_DIRIGEANT: "Berweiller",
  DIPLOME_DIRIGEANT: "couvreur-zingueur diplome, compagnon du devoir",
  ANNEE_CREATION: "2025",
  ANNEES_EXPERIENCE: "1",
  TELEPHONE: "06 65 76 68 70",
  EMAIL: "kevinvanbeen@gmail.com",
  ADRESSE: "7 rue du Pont Rodinet",
  CODE_POSTAL: "51490",
  VILLE: "Époyé",
  DEPARTEMENT: "Marne",
  REGION: "Champagne-Ardenne",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 7h30-18h00, Sam: 8h00-13h00",
  ZONE_INTERVENTION: "Marne et Île-de-France",
  ZONES_LISTE: "Époyé, Aÿ, Mardeuil, Cumières, Dizy, Mareuil-sur-Aÿ",
  LATITUDE: "48.8236",
  LONGITUDE: "3.7233",
  COULEUR_PRIMAIRE_HUE: "220",
  COULEUR_PRIMAIRE_900: "oklch(0.22 0.06 220)",
  COULEUR_ACCENT_HUE: "25",
  COULEUR_ACCENT_500: "oklch(0.64 0.16 25)",
  COULEUR_FOND_50: "oklch(0.985 0.005 80)",
  FONT_TITRES: "Playfair Display",
  FONT_CORPS: "DM Sans",
  DOMAINE: "www.kb-couverture.fr",
  META_TITLE: "K.B. COUVERTURE | Couvreur Époyé (51)",
  META_DESCRIPTION: "K.B. COUVERTURE - Couvreur professionnel à Époyé. Couverture neuve, rénovation toiture, zinguerie, isolation, dépannage d'urgence. Devis gratuit.",
  META_KEYWORDS: "couvreur Époyé, couverture toiture, rénovation toiture Marne, zinguerie, dépannage toiture urgent",
  SCHEMA_TYPE: "RoofingContractor",
  SLOGAN: "Votre Toiture, Notre Expertise",
  ACCROCHE_HERO: "Votre Toiture — Entre de Bonnes Mains",
  DESCRIPTION_ENTREPRISE: "K.B. COUVERTURE est un artisan couvreur basé à Époyé en Marne. Spécialisé dans la couverture neuve, la rénovation de toiture, la zinguerie et l'isolation. Nous intervenons rapidement pour tous vos besoins en couverture.",
  DESCRIPTION_FOOTER: "K.B. COUVERTURE - Artisan couvreur à Époyé depuis 2025. Nous assurons la qualité et la durabilité de vos toitures.",
  DESCRIPTION_APROPOS: "K.B. COUVERTURE a été créée par Kévin Berweiller, un artisan passionné par les métiers de la couverture et du bâtiment. Fort de son savoir-faire, Kévin propose des solutions durables et qualitatives pour tous vos projets de toiture.",
  SERVICE_1_TITRE: "Couverture Neuve",
  SERVICE_1_DESC: "Installation complete de votre toiture en ardoise, tuile ou zinc, avec une finition soignee et durable.",
  SERVICE_2_TITRE: "Renovation de Toiture",
  SERVICE_2_DESC: "Refection partielle ou totale de votre couverture pour redonner etancheite et esthetique a votre toit.",
  SERVICE_3_TITRE: "Zinguerie",
  SERVICE_3_DESC: "Pose et reparation de gouttieres, descentes EP, cheneaux, noues et abergements en zinc ou cuivre.",
  SERVICE_4_TITRE: "Isolation de Toiture",
  SERVICE_4_DESC: "Isolation thermique par l'interieur ou l'exterieur (sarking) pour ameliorer le confort et reduire la facture energetique.",
  SERVICE_5_TITRE: "Depannage & Urgence",
  SERVICE_5_DESC: "Intervention rapide pour fuites, tuiles cassees, bachage d'urgence et reparations suite a intemperies.",
  SERVICE_6_TITRE: "Demoussage & Entretien",
  SERVICE_6_DESC: "Nettoyage, traitement anti-mousse et hydrofuge pour prolonger la duree de vie de votre toiture.",
  GOOGLE_MAPS_URL: "",
  GOOGLE_REVIEWS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  PINTEREST_URL: "",
  TEMOIGNAGE_1_NOM: "M. Dupont",
  TEMOIGNAGE_1_VILLE: "Époyé",
  TEMOIGNAGE_1_TEXTE: "K.B. COUVERTURE a refait entierement notre toiture en ardoise. Le travail est impeccable, l'equipe ponctuelle et soigneuse. Nous recommandons les yeux fermes !",
  TEMOIGNAGE_1_NOTE: "5",
  TEMOIGNAGE_2_NOM: "Mme Bernard",
  TEMOIGNAGE_2_VILLE: "Aÿ",
  TEMOIGNAGE_2_TEXTE: "Intervention rapide apres une fuite. Diagnostic precis, reparation efficace et prix honnete. Un vrai professionnel de la couverture.",
  TEMOIGNAGE_2_NOTE: "5",
  TEMOIGNAGE_3_NOM: "M. Lefevre",
  TEMOIGNAGE_3_VILLE: "Mardeuil",
  TEMOIGNAGE_3_TEXTE: "Renovation complete de notre zinguerie. Gouttieres en zinc posees avec un soin remarquable. Aucun probleme depuis, meme apres de fortes pluies.",
  TEMOIGNAGE_3_NOTE: "5",
  HEBERGEUR_NOM: "Vercel Inc.",
  HEBERGEUR_ADRESSE: "340 Pine Street, Suite 701, San Francisco, CA 94104, USA",
  HEBERGEUR_SITE: "vercel.com",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
  PACK_PHOTOS_METIER: "couvreur",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
